name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-22.04
    steps:
      - name: echo a string
        run: echo "Hello, World"
      - name: multiline script
        run: |
          python3 -V
          python3 -c 'print("Im a Python script")'
      - name: Python Command
        shell: python
        run: |
          import platform
          print(platform.processor())
  run-windows-command:
    runs-on: windows-2022
    needs:
      - run-shell-command
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bahs
        run: pwd
        shell: bash