name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-22.04
    steps:
      - name: echo a string
        run: eecho "Hello, World"
      - name: multiline script
        run: |
          python3 -V
          python3 -c 'print("Im a Python script")'
